services:
    sblum.exception_enricher:
        class: ExceptionEnricher\Processor\ExceptionEnricherProcessor
        arguments: ["@request_stack", "@session", "@security.token_storage"]
        tags:
            - { name: monolog.processor }
