services:
    sblum.exception_enricher:
        class: ExceptionEnricher\Processor\ExceptionEnricherProcessor
        arguments:  ["@request_stack", "@session"]
        tags:
            - { name: monolog.processor }
